name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    concurrency: 
      group: ${{ github.ref }}
      cancel-in-progress: true

    runs-on: ubuntu-latest
    steps:
      # vmmeter start
      - uses: alexellis/arkade-get@master
        with:
          crane: latest
          print-summary: false

      - uses: docker/setup-buildx-action@v3

      - uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Get git commit
        id: get_git_commit
        run: echo "GIT_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - name: Get version
        id: get_version
        run: echo "VERSION=$(git describe --tags --dirty)" >> $GITHUB_ENV
      - name: Get Repo Owner
        id: get_repo_owner
        run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" > $GITHUB_ENV

      - name: Build containers
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          outputs: "type=image,push=false"
          platforms: linux/amd64,linux/arm64
          build-args: |
            GIT_COMMIT=${{env.GIT_COMMIT}}
            VERSION=${{env.VERSION}}
          tags: |
            ghcr.io/${{ env.REPO_OWNER  }}/slicer-ssh-agent:${{ github.sha }}
